Clash/time series
Azure/AzureMonitorForSAPSolutions pull request #113
Opened 2020-08-26 14:27 UTC by msclash

This is the support for the time series in the SQL Provider and the fix for the actions backup and errorlog. During this I found a fix for the error ('NoneType' object is not iterable) at multiple resultset queries.

2020-08-26 16:48 UTC, PakDLiu submitted a review, later dismissed

2020-09-01 12:21 UTC, tniek requested changes
I've added a few edits to make time-series queries work. Let's have a call to discuss in more detail.

2020-09-01 12:21 UTC, tniek commented on sapmon/payload/provider/sqlserver.py
> +      sqlTimestamp = ", GETDATE() AS %s, GETUTCDATE() AS %s, GETUTCDATE() AS %s FROM" % (COL_LOCAL_UTC,COL_SERVER_UTC,COL_TIMESERIES_UTC)
```suggestion
      sqlTimestamp = ", GETUTCDATE() AS %s, GETUTCDATE() AS %s FROM" % (COL_SERVER_UTC,COL_TIMESERIES_UTC)
```
We only need COL_SERVER_UTC here:
- COL_LOCAL_UTC is the current UTC time of the collector VM (this is fetched via `datetime.utcnow()` in function `updateState()`
- COL_TIMESERIES_UTC is the column in the result set of a time-series query that stores the past UTC time of the particular row

2020-09-01 12:21 UTC, tniek commented on sapmon/payload/provider/sqlserver.py
> +         preparedSql = sql
Not ideal, since `_prepareSql()` should be able to prepare any query (both time-series and point-in-time).
If your point-in-time queries do not require any transformations, we can keep this for now, though.

2020-09-01 12:21 UTC, tniek commented on sapmon/payload/provider/sqlserver.py
> +
```suggestion
      # Marking which column will be used for TimeGenerated
      self.colTimeGenerated = COL_TIMESERIES_UTC if isTimeSeries else COL_SERVER_UTC
```
We need to set `colTimeGenerated` here depending on the type of query

2020-09-01 12:21 UTC, tniek commented on sapmon/content/MsSqlServer.json
> +						"sql": "select t.database_name as DBName,case t.type when N'D' then N'Full' when N'F' then N'File' when N'G' then N'Filegroup' when N'I' then N'Differential' when N'L' then N'Log' end as Backup
As this is a time-series query, we need to alias one column (the one with the timestamps) as `_TIMESERIES_UTC`

2020-09-01 12:21 UTC, tniek commented on sapmon/content/MsSqlServer.json
> +						"sql": "SELECT CAST(xet.target_data as xml) as XMLDATA INTO #SystemHealthSessionData FROM sys.dm_xe_session_targets xet JOIN sys.dm_xe_sessions xe ON (xe.address = xet.event_session_address) WH
As this is a time-series query, we need to alias one column (the one with the timestamps) as `_TIMESERIES_UTC`

2020-11-01 17:54 UTC, tniek approved these changes
Looks good now

2020-11-04 16:30 UTC, persiaAziz approved these changes

2020-11-04 16:33 UTC, merged