Enable NW RFC SDK download, install, and RFC metric collection for Netweaver provider
Azure/AzureMonitorForSAPSolutions pull request #153
Opened 2021-03-24 00:57 UTC by MikeFrei

**Overview**
Enable AMS Netweaver Provider to download and a customer-provided NW RFC SDK to the collector VM container and install during Add Provider and Monitor runtime.  If install is successful and the python pyrfc module can be imported successfully, then netweaver provider will enable additional metric collection checks via RFC calls to fetch SMON and SWNC workload data.  At current time, it is optional for customer to do additional manual setup to enable RFC metric collection.

**Summary of changes:**

1.) adding RfcSdkInstaller class to encapsulate logic around RFC SDK download and installation state.  Validates if RFC is currently installed and usable via attempting to import the pyrfc module.  If customer provides necessary provider config settings to enable RFC SDK usage, including a blob URL to a customer-provided .zip file of the RFC SDK itself, then will attempt to download, install, and setup necessary environment variables.  Persists state to disk in between sapmon runs so that we can limit how often we try to do installation if previous attempt has failed (because installation steps are expensive)

2.) Adding abstract base class and netweaver metric client factory to encapsulate/isolate runtime module imports to pyrfc.  Allows sapmon netweaver provider class to take only take direct dependency on the abstract base class rather than the rfcclient. 
 (which would require importing of the pyrfc module, which may fail if the RFC SDK is not installed).  Abstract base class interface allows for abstraction of netweaver metric client implementation behind friend metric collection APIs like getSmonMetrics and getSwncWorkloadMetrics.  Intention behind this abstract is to enable unit test mocking in the future and better support for future metric client implementations that use OData instead of RFC.

3.) adding rfcclient class to encapsulate direct pyrfc module dependency and implement the NetweaverMetricClient abstract base class interface. Encapsulates functionality to establish RFC connection, make RFC calls, parse the responses, and decorate responses with additional common metric attributes for Azure Monitor.

4.) Additional functionality to sapmon Netweaver provider instance class to support singleton installation of RFC SDK during add provider (validation) and monitor runtimes, via the RfcSdkInstaller.  Exposes flag to provider check methods to know whether RFC SDK metric collection should be enabled.

5.) Extensive refactoring to existing Netweaver provider instance and provider check classes to more cleanly support a design where client functionality is encapsulated outside of the check methods.  This makes add provider and some monitor runtime dependencies go through provider instance API to get instance metadata.  Also enables us to centralize client caching inside the provider, and this change in particular cuts down on a significant amount of unnecessary SOAP API wsdl calls that were being made on each check (and corresponding log noise) when in fact these clients just needed to be instantiated once per run.

6.) fixed minor bug in the tracing code that sets up the QueueLogHandler that was causing log messages emitted to local disk trace file to have the correct/expected string formatting applied, but when emitted to the QueueLogHandler during production scenarios the log message would not have any of the string format arguments applied.  This meant we were breaking the logging API contract to support calls like info(format, *args).

7.) Minor rename of AzureStorageQueue wrapper to AzureStorageAccount since this was not really doing anything specific to a queue other than holding a queue name property.

8.) extensive cleanup of Netweaver provider instance and provider check class logging calls to have common prefix that includes SID so that we can more easily debug operational logs.

9.) changes to AMS collector VM docker container to install the pynwrfc module wheel as part of container build, and also ensure that RFC SDK libraries can be found in library load path by pyrfc module if they are extracted during runtime.

2021-03-24 17:41 UTC, persiaAziz commented
How did you test these changes?

2021-03-24 17:47 UTC, MikeFrei commented
> How did you test these changes?

persiaAsiz, tesing was done initially via running sapmon in debug session with VS Code remote SSH session.  This required making /etc/hosts file changes manually via sudo.  In the last couple weeks, testing was done via building container from our git feature branch and then running docker run with the same arguments that AMS has in your deployment .go scripts

2021-03-24 17:48 UTC, MikeFrei commented
> > How did you test these changes?
> 
> persiaAsiz, tesing was done initially via running sapmon in debug session with VS Code remote SSH session. This required making /etc/hosts file changes manually via sudo. In the last couple weeks, testing was done via building container from our git feature branch and then running docker run with the same arguments that AMS has in your deployment .go scripts

Just to clarify, testing was done on Add Provider and Monitor functionality.

2021-03-24 17:49 UTC, persiaAziz commented on sapmon/payload/netweaver/rfcsdkinstaller.py
> +if (os.name == "nt"):
Do we need this? We will always use Linux

2021-03-24 17:52 UTC, MikeFrei commented on sapmon/payload/netweaver/rfcsdkinstaller.py
> +if (os.name == "nt"):
This library was written in a manner so as to not have dependency on running within sapmon framework.  So your statement may be true for sapmon but I would like to leave this in there because supporting other platforms is not a bad thing.  Also enabled easier initial debugging from windows corpnet laptop via a direct test script and not having to run through the sapmon framework.

2021-03-24 18:09 UTC, persiaAziz commented on Docker/2.11/Dockerfile
> +FROM python:3.7-slim
I would highly recommend to put the release related changes in a later PR when this is ready to be publised. Right now we don't know that we will release this with 2.11. We may have hotfixes in the mean time.

2021-03-24 18:09 UTC, persiaAziz commented on Docker/2.11/Dockerfile
> +FROM python:3.7-slim
We keep our release changes in a different PR like this: https://github.com/Azure/AzureMonitorForSAPSolutions/pull/149/files

2021-03-24 18:09 UTC, persiaAziz commented on Docker/2.11/Dockerfile
> +FROM python:3.7-slim
You can for now change the dockerfile under master

2021-03-24 18:13 UTC, MikeFrei commented on Docker/2.11/Dockerfile
> +FROM python:3.7-slim
Okay this is a good point, I was trying to save you some time.  The pattern seemed to be that if docker file changes are needed then a new physical docker file needs to be created.  I did not notice there was one under master.  I will back out the 2.11/* changes and just make the dockerfile changes there.

2021-03-24 18:40 UTC, PakDLiu requested changes

2021-03-24 18:40 UTC, PakDLiu commented on sapmon/payload/netweaver/rfcsdkinstaller.py
> +            #blobClient = BlobClient.from_blob_url(blob_url=blobUrl, credential=storageAccount.getAccessKey())
Why are there some commented code in this method?

2021-03-24 18:40 UTC, PakDLiu commented on sapmon/payload/provider/sapnetweaver.py
> +            "retries": 1,
this change means there would be no retries at all.
Is that because the rfc validation take too long?

2021-03-24 18:40 UTC, PakDLiu commented on sapmon/payload/provider/sapnetweaver.py
> +        if (useCache and url in self._soapClientCache):
Just a note, this cache doesn't persist through container restarts
I am guessing this is just a minor improvement to the runtime

2021-03-24 18:40 UTC, PakDLiu commented on sapmon/payload/provider/sapnetweaver.py
> +        result = client.getSmonMetrics(startDateTime=startTime, endDateTime=endTime)
```suggestion
        client.getSmonMetrics(startDateTime=startTime, endDateTime=endTime)
```

2021-03-24 18:40 UTC, PakDLiu commented on sapmon/payload/provider/sapnetweaver.py
> +        result = client.getSwncWorkloadMetrics(startDateTime=startTime, endDateTime=endTime)
```suggestion
        client.getSwncWorkloadMetrics(startDateTime=startTime, endDateTime=endTime)
```

2021-03-24 19:08 UTC, MikeFrei commented on sapmon/payload/helper/azure.py
> +class AzureStorageAccount():
it is required for the the RFC SDK installer component because I am relying on the user having uploaded the RFC SDK to a blob.  The RFC SDK installer attempts to enumerate blob metadata get the last_modified property and it uses that timestamp to compare against to see if we should attempt to download the blob again.  It would be bad design for me to copy all this code into a different wrapper class just so I could leverage MSI to access storage account keys in the same way.  It would also be bad design for me to make up a bogus queue name and use this existing class just to access the storage account key.  Better design was to go ahead and modify the class so that it is just for storage account, since that is what it actually is anyway.

2021-03-24 19:09 UTC, MikeFrei commented on sapmon/payload/helper/tracing.py
> +      # and args escaping will be done by logging API.  For this customer JSON formatter, need to
thanks will fix!

2021-03-24 19:18 UTC, MikeFrei commented on sapmon/payload/netweaver/rfcsdkinstaller.py
> +            #blobClient = BlobClient.from_blob_url(blob_url=blobUrl, credential=storageAccount.getAccessKey())
ah... yes because weeks back when I was testing original implementation (before I started building as container) I had done a pip install of the latest azure storage blob package.  About 5 years ago completely rewrote the API surface area for interacting with storage resources several years back and split into multiple packages.  All the current documentation examples interact with blobs via the BlobClient class.  The BlockBlobService class does not exist anymore.

As I discovered when I first moved to container testing, we are fixed on a 5+ year old 0.36 version of this client that is really out of date, but unfortunately this BlockBlobService is directly referenced by the logging library we use, so I had to go back and rewrite these methods to use the v0.36 version of azure-storage APIs rather than the current ones.  Sorry I will cleanup these comments.

2021-03-24 19:28 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +        if (useCache and url in self._soapClientCache):
Yes, and non-trivial improvement during runtime.  The current design was actually really inefficient in that it was attempt to go out and fetch the SOAP WSDL for every single SOAP API call.  So in a typical run we would call the following 5 APIs, totaling roughly 2-3x N SOAP API calls, where N is number of instances.  Each of those API calls we would first have to fetch the SOAP WSDL, then we would make the API call itself.  So roughly 4-6x N total off-box calls.

GetSystemInstanceList (~1x time)
GetProcessList (N times)
ABAPGetWPTable (< N times)
GetQueueStatistic (< N times)
EnqGetStatistic (~ 1x)

So by caching the initialized WSDL client on first attempt, we are roughly reducing our off-box calls by 30-40%.  Also has benefit of reducing log spam.

2021-03-24 19:47 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +            "retries": 1,
yes this was intentional.  What I discovered during earlier testing is that the RFC SDK does not allow client to specify a timeout and in fact appears to have a connection timeout of 60 secs.  Due to earlier misconfiguration, I ran into case where some SIDs I was trying to connect to instance that could not accept RFC calls and the check would take 3 minutes to execute before failing.

So basically I am making the assertions here that it is extremely rare for a SOAP or RFC call to fail on first call and succeed on a retry, and that usually the failure will be due to some persistent issue.  And in this case, it is better to not waste time on retry rather than have long wait intervals that will actually result in metric collection gaps.

2021-03-24 19:47 UTC, PakDLiu commented on sapmon/payload/helper/azure.py
> +class AzureStorageAccount():
> It would be bad design for me to copy all this code into a different wrapper class just so I could leverage MSI to access storage account keys in the same way. It would also be bad design for me to make up a bogus queue name and use this existing class just to access the storage account key. Better design was to go ahead and modify the class so that it is just for storage account, since that is what it actually is anyway.

I agree, but I was asking why we need to change the kay handling logic, is it because iterating through the metadata requires multiple API calls and we should cache the key? or something else?

2021-03-24 19:48 UTC, MikeFrei commented on Docker/2.11/Dockerfile
> +RUN mkdir -p /var/opt/microsoft/sapmon/${RELEASE}/sapmon/usrlibs/nwrfcsdk/nwrfcsdk/lib
Right, this is in the container only and that was intention, and it will bet reinstalled to container at runtime each time new container is started.  We do not currently have any agent or service running on the host that I could have leveraged to reliably install the RFC SDK on host and/or periodically poll for updates.  Since that does not exist in the system today, doing it more deterministically in the container seems like the best option.

2021-03-24 19:51 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +        result = client.getSmonMetrics(startDateTime=startTime, endDateTime=endTime)
the result variable is actually used in the finally block.  I guess this was an optimization on my part so that I did not have to set self.lastResult twice.  But actually with your suggestion could probably just get rid of the finally clause completely.  Will change.

2021-03-24 20:09 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +        result = client.getSmonMetrics(startDateTime=startTime, endDateTime=endTime)
fixed

2021-03-24 20:09 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +        result = client.getSwncWorkloadMetrics(startDateTime=startTime, endDateTime=endTime)
fixed

2021-03-24 20:09 UTC, MikeFrei commented on sapmon/payload/netweaver/rfcsdkinstaller.py
> +            #blobClient = BlobClient.from_blob_url(blob_url=blobUrl, credential=storageAccount.getAccessKey())
fixed

2021-03-24 20:26 UTC, MikeFrei commented on sapmon/payload/helper/azure.py
> +class AzureStorageAccount():
ah sorry I understand what you mean now.  You're referring to allowing accountKey to be passed  in the constructor.  This was because I was blocked for a bit in testing because the MSI on our collector VM had become detached from the storage account permissions and suddenly I was no longer able to run the code.  So I added accountKey as an optional arg to enable me to pass it directly and bypass MSI if I needed to.  It also made some testing easire from my corpnet laptop which did not have an MSI.  If you want, I can remove.

2021-03-24 20:26 UTC, MikeFrei commented on Docker/2.11/Dockerfile
> +FROM python:3.7-slim
have updated const.py PAYLOAD_VERSION as well and reverted back to 2.10.

2021-03-24 20:27 UTC, MikeFrei commented on sapmon/content/SapNetweaver.json
> +            "includeInCustomerAnalytics": true,
No, only SID, Hostname and instance name.  no different from our other metrics.  Yes I will fill out that doc.

2021-03-24 20:31 UTC, MikeFrei commented on sapmon/payload/helper/azure.py
> +class AzureStorageAccount():
i have removed the accountKey override stuff.

2021-03-24 20:39 UTC, PakDLiu commented on Docker/2.11/Dockerfile
> +RUN mkdir -p /var/opt/microsoft/sapmon/${RELEASE}/sapmon/usrlibs/nwrfcsdk/nwrfcsdk/lib
ack

2021-03-24 20:39 UTC, MikeFrei commented on Docker/2.11/Dockerfile
> +RUN mkdir -p /var/opt/microsoft/sapmon/${RELEASE}/sapmon/usrlibs/nwrfcsdk/nwrfcsdk/lib
oh wait donald you are suggesting that we could mount the directory from the host as writeable, then when the container downloads it there it will persist between new container deployments.  Yes I see your point and I agree, it is a good idea.  I think it would work just by updating a couple of the path variable constants, then making sure the docker commands were updated.  This would be a good optimization especially for frequent Add provider operations.  Can we table this idea for a future change?  Thank you for pointing this out.

2021-03-24 20:40 UTC, PakDLiu commented on sapmon/payload/provider/sapnetweaver.py
> +            "retries": 1,
That's fair, can you add a comment stating the reasoning?

2021-03-24 20:48 UTC, PakDLiu commented on Docker/2.11/Dockerfile
> +RUN mkdir -p /var/opt/microsoft/sapmon/${RELEASE}/sapmon/usrlibs/nwrfcsdk/nwrfcsdk/lib
Yes, that's was what I was proposing, but it might be an unneeded optimization. Could be a future update if needed

2021-03-24 20:59 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +            "retries": 1,
done

2021-03-25 18:46 UTC, PakDLiu submitted a review, later dismissed

2021-03-26 18:18 UTC, PakDLiu approved these changes

2021-03-26 19:43 UTC, MikeFrei commented on sapmon/content/SapNetweaver.json
> +            "includeInCustomerAnalytics": true,
have finished filling this out

2021-04-05 21:26 UTC, persiaAziz approved these changes

2021-04-07 15:25 UTC, PakDLiu approved these changes

2021-04-07 17:30 UTC, persiaAziz approved these changes

2021-04-07 19:50 UTC, merged