Merging azure/master to heartbeat branch
Azure/AzureMonitorForSAPSolutions pull request #168
Opened 2021-04-30 23:24 UTC by bluereign

Adding a heartbeat signal to telemetry to aid in debugging and service health.  

**Output with consist of the following structure/json for provider checks:**

_{
  "Count": 12,
  "Providers": [
    {
      "Name": "SapNetweaver",
      "Checks": [
        {
          "Name": "GetSystemInstanceList",
          "Duration": 6477,
          "Success": true,
          "Message": null
        },
        {
          "Name": "GetProcessList",
          "Duration": 5968,
          "Success": true,
          "Message": null
        },
        {
          "Name": "ABAPGetWPTable",
          "Duration": 5512,
          "Success": true,
          "Message": null
        },
        {
          "Name": "GetQueueStatistic",
          "Duration": 5821,
          "Success": true,
          "Message": null
        },
        {
          "Name": "EnqGetStatistic",
          "Duration": 5141,
          "Success": true,
          "Message": null
        },
        {
          "Name": "SMON_Metrics",
          "Duration": 3691,
          "Success": true,
          "Message": null
        },
        {
          "Name": "SWNC_Workload_Metrics",
          "Duration": 1136,
          "Success": true,
          "Message": null
        },
        {
          "Name": "SDF_Short_Dumps_Metrics",
          "Duration": 1728,
          "Success": true,
          "Message": null
        }
      ]
    }
  ]
}_

**Kusto query to see this data:**

_SapMonitorActivity
| where TIMESTAMP between (datetime(2021-04-28 17:42:00.0000000)..datetime(2021-04-28 20:47:00.0000000))
//| where TIMESTAMP >= ago(1h)
| extend m = parse_json(message)
| extend module = m.module
| extend f = m.function
| where f == "heartbeat"
| extend heartbeatMessage = tostring(m.msg)
| extend heartbeatJson = todynamic(heartbeatMessage)
| extend providers = tostring(heartbeatJson.Providers)
| extend dynamicProvider = todynamic(providers)
| mv-expand expandedProvider = dynamicProvider
| extend checks = tostring(expandedProvider.Checks)
| extend dynamicCheck = todynamic(checks)
| mv-expand expandedCheck = dynamicCheck
| extend CheckDuration = toint(expandedCheck.Duration)
| extend ProviderName = tostring(expandedProvider.Name)
| extend Check = tostring(expandedCheck.Name)
| extend Success = tostring(expandedCheck.Success)
| extend CheckMessage = tostring(expandedCheck.Message)
| project TIMESTAMP, heartbeatJson, ProviderCount=heartbeatJson.Count, ProviderName, Check, CheckDuration, Success, CheckMessage
| order by TIMESTAMP desc_

**Sample dashboard**
https://jarvis-west.dc.ad.msft.net/dashboard/GTMSAPAMSMon/Sample

2021-05-03 17:24 UTC, PakDLiu requested changes

2021-05-03 17:24 UTC, PakDLiu commented on sapmon/payload/sapmon.py
> +   concurrent.futures.wait(futures)
The loop in line 213 is ran every 5 seconds.
Checks will be continuously be submitted to the thread pool (in turn in futures). There are long running checks that may always get submitted to the thread pool, when that happens futures will never be empty.
It looks like the heartbeat method gets submitted to the thread pool on every iteration of the loop (every 5 seconds), and the heartbeat method will wait for all the checks to completed in futures (this line).
If future is never empty, this line will always get stuck, no?

2021-05-03 17:24 UTC, PakDLiu commented on sapmon/payload/sapmon.py
> +               "Duration": check.duration,
it seems like check.duration is over written each time that check is ran, and only emit the duration of the latest run. So for checks that run, say once a day, it will always emit the same duration?

2021-05-03 17:54 UTC, bluereign commented on sapmon/payload/sapmon.py
> +   concurrent.futures.wait(futures)
Will a long running check fail any of following if conditions:
         if check.getLockName() in ctx.checkLockSet:
            tracer.info("[%s] already queued/executing, skipping" % check.fullName)
            continue
         elif not check.isEnabled():
            tracer.info("[%s] not enabled, skipping" % check.fullName)
            continue
         elif not check.isDue():
            tracer.info("[%s] not due for execution, skipping" % check.fullName)
            continue

if a long running check does get pass the above if conditions then I do need to redo this line.  My understanding was that a check that is currently executing won't get called again.

2021-05-03 17:55 UTC, bluereign commented on sapmon/payload/sapmon.py
> +               "Duration": check.duration,
Good point, I was trying to avoid having to pass another array of current checks being executed but it looks like I can avoid passing something else to the heartbeat method

2021-05-03 18:03 UTC, PakDLiu commented on sapmon/payload/sapmon.py
> +   concurrent.futures.wait(futures)
Long running checks will not pass the `if check.getLockName() in ctx.checkLockSet:` check.
My concern is that future may never be empty. IE, when there is a large number of checks queued up, and some checks get requeued before the queue is empty.

I can think of 2 options (there may be more):
1. Heartbeat method to not be async. It can just emit all the checks that completed in the last 5 seconds, on every iteration of the loop, or something like that (maybe every 1 minute?)
2. Remove the `concurrent.futures.wait(futures)` line and the Heartbeat method could act like a normal check and run whenever it gets ran.

2021-05-03 19:31 UTC, bluereign commented on sapmon/payload/sapmon.py
> +   concurrent.futures.wait(futures)
I like the idea of putting the heartbeat on an interval and removing the futures[], my concern with that is what if a check gets executed more than once between heartbeat intervals and it may have failed once, we would only get the last execution info of the check with the heartbeat check.

2021-05-03 19:40 UTC, PakDLiu commented on sapmon/payload/sapmon.py
> +   concurrent.futures.wait(futures)
That is unlikely, since the minimum frequency for a check is 1 minute, and the heartbeat should emit at least once a minute.
Also, check failures will still be logged, so it's not lost

2021-05-05 16:45 UTC, PakDLiu approved these changes

2021-05-06 17:48 UTC, merged