Syslog Provider Implementation
Azure/AzureMonitorForSAPSolutions pull request #183
Opened 2021-07-07 01:22 UTC by djhamb

Implemented Syslog Provider using td-agent.

2021-07-07 16:56 UTC, persiaAziz requested changes

2021-07-07 16:56 UTC, persiaAziz commented on Docker/master/Dockerfile
> +# RUN ACCEPT_EULA=Y apt-get install msodbcsql17 -y
Why is this being commented out? We need this for sql provider

2021-07-07 16:56 UTC, persiaAziz commented on sapmon/content/Syslog.json
> +            "description": "No-op",
You can still put a one-line description of syslog provider

2021-07-07 16:56 UTC, persiaAziz commented on sapmon/payload/provider/syslog.py
> +    def restartTdAgent(self) -> bool:
We will need to add error handling here

2021-07-08 19:47 UTC, persiaAziz commented on sapmon/payload/provider/syslog.py
> +        with open(TD_AGENT_CONFIG_PATH, "w") as config_file:
please add error handler  here as well

2021-07-08 19:53 UTC, PakDLiu commented on sapmon/payload/provider/syslog.py
> +            subprocess.run(['service', 'td-agent', 'restart'])
Looks like you are calling restart when the provider is initialized, does that mean td-agent is already started when the container starts? or will the restart command actually start td-agent?

2021-07-08 20:47 UTC, djhamb commented on sapmon/payload/provider/syslog.py
> +            subprocess.run(['service', 'td-agent', 'restart'])
Td-agent is already started when the container starts. The restart command is necessary to allow the changes to the td-agent config file to take effect. Any time the config is modified, the service has to be restarted.

2021-07-08 20:55 UTC, PakDLiu approved these changes

2021-07-08 22:06 UTC, persiaAziz approved these changes

2021-07-08 22:06 UTC, merged