Devanshjain/empty rfc exception
Azure/AzureMonitorForSAPSolutions pull request #188
Opened 2021-08-02 21:36 UTC by devanshjainms

When an RFC call returns empty records, the collector VM will check if there are any system errors and log them, and then return an empty list, instead of raising an exception. 
This was causing problems on RFC Preview where there was no data being returned by RFC calls and it was throwing an exception.

2021-08-02 21:55 UTC, PakDLiu requested changes
Also, can you comment on the testing you have done?

2021-08-02 21:55 UTC, PakDLiu commented on sapmon/payload/netweaver/rfcclient.py
> +        if len(server_error_records) != 0:
Why is this If needed?

2021-08-02 21:55 UTC, PakDLiu commented on sapmon/payload/netweaver/rfcclient.py
> +                self.tracer.info(("%s RFC Name: %s, System ID: %s, Instance: %s, Error: %s"), self.logTag, rfcName, error["SYSTEMID"], error["INSTANCE"], error["ERROR_TEXT"])
If these are errors, should tracer log them on error level instead?

2021-08-02 21:55 UTC, PakDLiu commented on sapmon/payload/netweaver/rfcclient.py
> +        if self._isRFCRecordEmpty(rfcName, records, server_error_records):
It seems like `_isRFCRecordEmpty` will log any errors in `server_error_records`, then returns true if `records` is empty.
It is not immediately clear that `_isRFCRecordEmpty` also logs given the naming. It may be better to log the errors in `server_error_records` outside of this method.

2021-08-02 22:16 UTC, devanshjainms commented on sapmon/payload/netweaver/rfcclient.py
> +                self.tracer.info(("%s RFC Name: %s, System ID: %s, Instance: %s, Error: %s"), self.logTag, rfcName, error["SYSTEMID"], error["INSTANCE"], error["ERROR_TEXT"])
These may or may not be errors. They can be issues like no data found, or no jobs running, or system exception.

2021-08-02 22:25 UTC, devanshjainms commented on sapmon/payload/netweaver/rfcclient.py
> +        if self._isRFCRecordEmpty(rfcName, records, server_error_records):
I have logged the errors in `server_error_records ` inside this method so that this method can be used by other RFC Calls to handle this issue. The other way could be that I change the name of the function to `_checkEmptyRFCRecords`. Please suggest.

2021-08-02 22:28 UTC, devanshjainms commented on sapmon/payload/netweaver/rfcclient.py
> +        if len(server_error_records) != 0:
This is to check if there are any server errors that were returned by RFC Call and the other `if` checks if there are records returned by the RFC Call.

2021-08-02 22:38 UTC, devanshjainms commented
I have tested these changes in both scenarios where an SAP System has data so the RFC Calls return some data, and one where it was a new SAP System having no data, resulting in RFC Calls raising server errors (No Data Found). In both scenarios, the logs had come up as expected.

2021-08-03 01:26 UTC, PakDLiu requested changes

2021-08-03 01:26 UTC, PakDLiu commented on sapmon/payload/netweaver/rfcclient.py
> +        if len(server_error_records) != 0:
Sorry, I should have been more clear. I am implying this `if` is not necessary since if `server_error_records` is empty, it would not have gone in the for loop anyways

2021-08-03 01:26 UTC, PakDLiu commented on sapmon/payload/netweaver/rfcclient.py
> +                self.tracer.info(("%s RFC Name: %s, System ID: %s, Instance: %s, Error: %s"), self.logTag, rfcName, error["SYSTEMID"], error["INSTANCE"], error["ERROR_TEXT"])
I see, it may be more informative to rename `server_error_records` to something like `server_result_records`, or something like that

2021-08-03 01:26 UTC, PakDLiu commented on sapmon/payload/netweaver/rfcclient.py
> +        if self._isRFCRecordEmpty(rfcName, records, server_error_records):
Where else is `_isRFCRecordEmpty` also used?

My concern is that `_isRFCRecordEmpty` is doing more take the naming implies (it is also logging in addition to checking for empty `records`

2021-08-03 15:53 UTC, devanshjainms commented on sapmon/payload/netweaver/rfcclient.py
> +        if self._isRFCRecordEmpty(rfcName, records, server_error_records):
Since this has come up as a recent bug that needed to be fixed for this particular RFC call at priority, it has currently not been used with other RFC Calls. But we plan to use it with other RFC Calls, where there is a possibility of encountering a similar bug.
And for the logging part, having all methods (which have RFC Calls) make a similar log, it made more sense for me to have it encapsulated inside this function.

2021-08-03 15:57 UTC, devanshjainms commented on sapmon/payload/netweaver/rfcclient.py
> +        if len(server_error_records) != 0:
Okay. I get it now. I will get rid of that statement.

2021-08-09 15:06 UTC, merged